application: irssinotifier
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /script
  static_dir: script
- url: /.*
  script: main.app
  secure: always
libraries:
- name: jinja2
  version: latest
